# Generated by Django 5.2.12 on 2026-03-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_singlecall_singlecalllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='caller_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='caller_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
