# Generated by Django 5.2.12 on 2026-03-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_caller_id_singlecall_caller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlecall',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
