# Generated by Django 5.2.12 on 2026-03-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_singlecall_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='audio_file_goodbye',
            field=models.FileField(blank=True, null=True, upload_to='campaign_audio/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='audio_file_reprompt',
            field=models.FileField(blank=True, null=True, upload_to='campaign_audio/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='audio_file_timeout',
            field=models.FileField(blank=True, null=True, upload_to='campaign_audio/'),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='audio_file_goodbye',
            field=models.FileField(blank=True, null=True, upload_to='single_call_audio/'),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='audio_file_reprompt',
            field=models.FileField(blank=True, null=True, upload_to='single_call_audio/'),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='audio_file_timeout',
            field=models.FileField(blank=True, null=True, upload_to='single_call_audio/'),
        ),
    ]
