# Generated by Django 5.2.12 on 2026-03-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_audio_file_press1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='audio_file_onhold',
            field=models.FileField(blank=True, null=True, upload_to='campaign_audio/'),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='audio_file_onhold',
            field=models.FileField(blank=True, null=True, upload_to='single_call_audio/'),
        ),
    ]
