# Generated by Django 5.2.12 on 2026-03-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_singlecall_modes_and_template_tts_clips'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtsScriptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('greeting_script', models.TextField()),
                ('press1_script', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='singlecall',
            name='press1_tts_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='script_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_calls', to='campaigns.ttsscripttemplate'),
        ),
    ]
