# Generated by Django 5.2.12 on 2026-03-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_ttsscripttemplate_singlecall_press1_tts_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotemplate',
            name='goodbye_audio',
            field=models.FileField(blank=True, null=True, upload_to='question_templates/'),
        ),
        migrations.AddField(
            model_name='audiotemplate',
            name='greeting_script',
            field=models.TextField(blank=True, help_text='The full script for TTS + Custom Script mode.'),
        ),
        migrations.AddField(
            model_name='audiotemplate',
            name='mode',
            field=models.CharField(choices=[('audio_only', 'Audio Only'), ('tts_template', 'TTS + Template (Sandwich)'), ('tts_script', 'TTS + Custom Script')], default='audio_only', max_length=25),
        ),
        migrations.AddField(
            model_name='audiotemplate',
            name='onhold_audio',
            field=models.FileField(blank=True, null=True, upload_to='question_templates/'),
        ),
        migrations.AddField(
            model_name='audiotemplate',
            name='press1_audio',
            field=models.FileField(blank=True, null=True, upload_to='question_templates/'),
        ),
        migrations.AddField(
            model_name='audiotemplate',
            name='press2_audio',
            field=models.FileField(blank=True, null=True, upload_to='question_templates/'),
        ),
        migrations.AddField(
            model_name='audiotemplate',
            name='reprompt_audio',
            field=models.FileField(blank=True, null=True, upload_to='question_templates/'),
        ),
        migrations.AddField(
            model_name='audiotemplate',
            name='timeout_audio',
            field=models.FileField(blank=True, null=True, upload_to='question_templates/'),
        ),
        migrations.AddField(
            model_name='audiotemplate',
            name='validate_audio',
            field=models.FileField(blank=True, null=True, upload_to='question_templates/'),
        ),
        migrations.AlterField(
            model_name='audiotemplate',
            name='greeting_audio',
            field=models.FileField(blank=True, null=True, upload_to='question_templates/'),
        ),
        migrations.AlterField(
            model_name='audiotemplate',
            name='prompt_text',
            field=models.TextField(blank=True, help_text="The 'filling' for the TTS + Template sandwich."),
        ),
    ]
