# Generated by Django 5.2.12 on 2026-03-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_audiotemplate_goodbye_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotemplate',
            name='expected_digits',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='singlecall',
            name='dtmf_responses',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='singlecall',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
