# Generated by Django 5.2.12 on 2026-03-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_audiotemplate_expected_digits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiotemplate',
            name='goodbye_audio',
        ),
        migrations.RemoveField(
            model_name='audiotemplate',
            name='onhold_audio',
        ),
        migrations.RemoveField(
            model_name='audiotemplate',
            name='press1_audio',
        ),
        migrations.RemoveField(
            model_name='audiotemplate',
            name='press2_audio',
        ),
        migrations.RemoveField(
            model_name='audiotemplate',
            name='reprompt_audio',
        ),
        migrations.RemoveField(
            model_name='audiotemplate',
            name='timeout_audio',
        ),
        migrations.RemoveField(
            model_name='audiotemplate',
            name='validate_audio',
        ),
    ]
