# Generated by Django 5.2.12 on 2026-03-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_remove_audiotemplate_goodbye_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='mode',
            field=models.CharField(choices=[('audio_only', 'Audio Only'), ('tts_template', 'TTS + Template (Sandwich)'), ('tts_script', 'TTS + Custom Script')], default='audio_only', max_length=25),
        ),
    ]
