# Generated by Django 5.2.12 on 2026-03-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_questioncategory_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiotemplate',
            name='prompt_text',
        ),
        migrations.RemoveField(
            model_name='audiotemplate',
            name='tts_intro_audio',
        ),
        migrations.RemoveField(
            model_name='audiotemplate',
            name='tts_outro_audio',
        ),
        migrations.RemoveField(
            model_name='singlecall',
            name='tts_intro_file',
        ),
        migrations.RemoveField(
            model_name='singlecall',
            name='tts_outro_file',
        ),
        migrations.AlterField(
            model_name='audiotemplate',
            name='mode',
            field=models.CharField(choices=[('audio_only', 'Audio Only'), ('tts_script', 'TTS + Custom Script')], default='audio_only', max_length=25),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='mode',
            field=models.CharField(choices=[('audio_only', 'Audio Only'), ('tts_script', 'TTS + Custom Script')], default='audio_only', max_length=25),
        ),
        migrations.AlterField(
            model_name='singlecall',
            name='mode',
            field=models.CharField(choices=[('audio_only', 'Audio Only'), ('tts_script', 'TTS + Custom Script')], default='audio_only', max_length=20),
        ),
    ]
