# Generated by Django 5.2.12 on 2026-03-25 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_remove_audiotemplate_prompt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='category_type',
            field=models.CharField(choices=[('greeting', 'Main Greeting'), ('press1', 'Press 1 Prompt (Digit Entry)')], default='greeting', max_length=20),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='press1_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_calls_as_press1', to='campaigns.audiotemplate'),
        ),
    ]
