# Generated by Django 5.2.12 on 2026-03-26 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_questioncategory_category_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlecall',
            name='press1_tts_script',
        ),
        migrations.RemoveField(
            model_name='singlecall',
            name='script_template',
        ),
        migrations.RemoveField(
            model_name='singlecall',
            name='selected_template',
        ),
        migrations.RemoveField(
            model_name='singlecall',
            name='tts_script',
        ),
        migrations.AddField(
            model_name='singlecall',
            name='goodbye_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='goodbye_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_calls_goodbye', to='campaigns.audiotemplate'),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='greeting_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='greeting_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_calls_greeting', to='campaigns.audiotemplate'),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='onhold_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='onhold_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_calls_onhold', to='campaigns.audiotemplate'),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='press1_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='press2_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='press2_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_calls_press2', to='campaigns.audiotemplate'),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='reprompt_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='reprompt_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_calls_reprompt', to='campaigns.audiotemplate'),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='timeout_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='timeout_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_calls_timeout', to='campaigns.audiotemplate'),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='validate_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='singlecall',
            name='validate_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_calls_validate', to='campaigns.audiotemplate'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='category_type',
            field=models.CharField(choices=[('greeting', 'Main Greeting'), ('press1_prompt', 'Press 1 Prompt (Digit Entry)'), ('press2_prompt', 'Press 2 Prompt (Transfer)'), ('reprompt', 'Reprompt (Invalid Input)'), ('timeout', 'Timeout (No Input)'), ('validate', 'Validate (Processing)'), ('goodbye', 'Goodbye (End)'), ('onhold', 'On Hold (Music/Wait)')], default='greeting', max_length=20),
        ),
        migrations.AlterField(
            model_name='singlecall',
            name='press1_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_calls_press1', to='campaigns.audiotemplate'),
        ),
    ]
