# Generated by Django 5.2.12 on 2026-03-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_remove_singlecall_press1_tts_script_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='category_type',
            field=models.CharField(choices=[('greeting', 'Main Greeting'), ('press1', 'Press 1 Prompt (Digit Entry)'), ('press2', 'Press 2 Prompt (Transfer)'), ('reprompt', 'Reprompt (Invalid Input)'), ('timeout', 'Timeout (No Input)'), ('validate', 'Validate (Processing)'), ('goodbye', 'Goodbye (End)'), ('onhold', 'On Hold (Music/Wait)')], default='greeting', max_length=20),
        ),
    ]
