# Generated by Django 5.2.12 on 2026-03-26 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_alter_questioncategory_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlecall',
            name='tts_script_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_calls', to='campaigns.ttsscripttemplate'),
        ),
        migrations.AddField(
            model_name='ttsscripttemplate',
            name='goodbye_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ttsscripttemplate',
            name='onhold_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ttsscripttemplate',
            name='press2_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ttsscripttemplate',
            name='reprompt_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ttsscripttemplate',
            name='timeout_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ttsscripttemplate',
            name='validate_script',
            field=models.TextField(blank=True, default=''),
        ),
    ]
