# Generated by Django 5.2.12 on 2026-03-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_singlecall_tts_script_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttsscripttemplate',
            name='expected_digits',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
