# Generated by Django 5.2.12 on 2026-03-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0023_ttsscripttemplate_expected_digits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttsscripttemplate',
            name='onhold_script',
        ),
        migrations.AddField(
            model_name='ttsscripttemplate',
            name='onhold_audio',
            field=models.FileField(blank=True, null=True, upload_to='tts_onhold/'),
        ),
    ]
